/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectprogra2;


import clases.pacientes;
import clases.postgreeconexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anaca
 */
public class agregarpaciente extends javax.swing.JFrame {

    /**
     * Creates new form agregarpaciente
     */
    List<pacientes> listapacientes;
    pacientes paciente;
    
    public agregarpaciente() {
        initComponents();
        listapacientes = new ArrayList<>();
        paciente = new pacientes();
       // Actualizartabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nopaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        primerapellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        segundoapellido1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lugarnacimiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        alergias = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tiposangre = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        etnia = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        idioma = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        dpi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nivelescolar = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        ocupacionpaciente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        observacion = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        horaingreso = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        departamento = new javax.swing.JTextField();
        municipio = new javax.swing.JTextField();
        dia = new javax.swing.JComboBox<>();
        mes = new javax.swing.JComboBox<>();
        anio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(127, 181, 181));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel1.setText("No. Afiliado");

        jLabel2.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel2.setText("AGREGAR AFILIADO");

        nopaciente.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel3.setText("Primer Apellido");

        primerapellido.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel4.setText("Segundo Apellido");

        segundoapellido1.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        segundoapellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundoapellido1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel5.setText("Nombres");

        nombres.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel6.setText("DPI");

        jLabel7.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel7.setText("Fecha de nacimiento");

        jLabel8.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel8.setText("Lugar de nacimiento");

        lugarnacimiento.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel9.setText("Alergias");

        alergias.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        alergias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Alergia a alimentos.", "Alergia a fármacos.", "Asma alérgico.", "Dermatitis atópica.", "Poliposis nasal.", "Rinitis alérgica.", "Urticaria crónica." }));
        alergias.setName(""); // NOI18N

        jLabel10.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel10.setText("Tipo de Sangre");

        tiposangre.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        tiposangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Tipo A.", "Tipo B.", "Tipo AB.", "Tipo O." }));

        jLabel11.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel11.setText("Grupo Étnico");

        etnia.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        etnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "garífuna", "xinka", "achií", "akateco", "awakateco", "chalchiteco", "ch'orti'", "chuj ", "itzá", "ixil ", "jacalteco", "kaqchikel ", "k'iche'", "mam", "mopan", "poqomam", "poqomchi'", "q'anjob'al", "q'eqchi ", "sakapulteco", " sipakapense ", "tektiteko", " tz'utujil ", "uspanteko" }));

        jLabel12.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel12.setText("Idioma");

        idioma.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Inglés ", "Mandarín ", "Hindi", "Español ", "Francés ", "Árabe ", "Bengalí", "Ruso " }));

        jLabel13.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel13.setText("Sexo");

        sexo.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Masculino", "Femenino", " " }));

        dpi.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel14.setText("Nivel Escolar");

        nivelescolar.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        nivelescolar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "educación preprimaria (párvulos 1, 2 y 3)", "educación primaria", "educación media (ciclo de educación básica y ciclo de educación diversificada)", "educación universitaria" }));

        jLabel15.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel15.setText("Ocupacion Del Afiliado");

        ocupacionpaciente.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel16.setText("Departamento residencia");

        jLabel17.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel17.setText("Municipio residencia");

        jLabel18.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel18.setText("Direccion");

        direccion.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel19.setText("Telefono");

        telefono.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel20.setText("Email");

        email.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel21.setText("Observacion");

        observacion.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        jLabel22.setText("Hora de ingreso");

        horaingreso.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N

        agregar.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        atras.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        atras.setText("ATRAS");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        departamento.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        municipio.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        dia.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-DIA-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mes.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-MES-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        anio.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        anio.setText("año");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addComponent(nopaciente)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(segundoapellido1)
                                        .addComponent(nombres)
                                        .addComponent(primerapellido)
                                        .addComponent(jLabel7)
                                        .addComponent(lugarnacimiento)
                                        .addComponent(dpi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(jLabel8)))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(alergias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10)
                                    .addComponent(tiposangre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addComponent(etnia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addComponent(idioma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13)
                                    .addComponent(sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14)
                                    .addComponent(nivelescolar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15)
                                    .addComponent(ocupacionpaciente))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(direccion)
                                    .addComponent(jLabel19)
                                    .addComponent(telefono)
                                    .addComponent(jLabel20)
                                    .addComponent(email)
                                    .addComponent(jLabel21)
                                    .addComponent(observacion)
                                    .addComponent(jLabel22)
                                    .addComponent(horaingreso)
                                    .addComponent(departamento)
                                    .addComponent(municipio)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(atras)
                                .addGap(18, 18, 18)
                                .addComponent(agregar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(jLabel2)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tiposangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nivelescolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocupacionpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(primerapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(segundoapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lugarnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(observacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregar)
                            .addComponent(atras))
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void segundoapellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundoapellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segundoapellido1ActionPerformed

    
        
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
         paciente = new pacientes();
         if(nopaciente.getText().equals("")){
             lanzarMensaje("Debe ingresar No. del paciente");
         }else if(exiteNopaciente()){
             lanzarMensaje("El No. del paciente ingresado ya se encuentra registrado en el sistema");
         }else {
             
            String fecha;
         paciente.setNopaciente(nopaciente.getText());
         paciente.setPrimerapellido(primerapellido.getText());
         paciente.setSegundoapellido(segundoapellido1.getText());
         paciente.setNombres(nombres.getText());
         paciente.setDPI(dpi.getText());
         paciente.setFechanacimiento(anio.getText() +"-"+ mes.getSelectedItem().toString() +"-"+ dia.getSelectedItem().toString());
          fecha = (anio.getText() +"-"+ mes.getSelectedItem().toString() +"-"+ dia.getSelectedItem().toString());
        paciente.setEdad(paciente.calcularEdad(fecha));
         paciente.setLugarnacimiento(lugarnacimiento.getText());
         paciente.setTiposangre(tiposangre.getSelectedItem().toString());
         paciente.setEtnia(etnia.getSelectedItem().toString());
         paciente.setSexo(sexo.getSelectedItem().toString());
         paciente.setNivelescolar(nivelescolar.getSelectedItem().toString());
         paciente.setOcupacion(ocupacionpaciente.getText());
         paciente.setDepartamento(departamento.getText());
         paciente.setMunicipio(municipio.getText());
         paciente.setDireccion(direccion.getText());
         paciente.setTelefono(telefono.getText());
         paciente.setEmail(email.getText());
         paciente.setObservacion(observacion.getText());
         paciente.setHoraingreso(horaingreso.getText());
         paciente.setIdioma(idioma.getSelectedItem().toString());
         paciente.setAlergias(alergias.getSelectedItem().toString());
         
        listapacientes.add(paciente);
         
         
              postgreeconexion conexion = new postgreeconexion();
            Connection CONEXION = conexion.connectarPostgree();
            
             try {
                    String SQL = "INSERT INTO public.registro"
                 +"(no_paciente, primer_apellido, segundo_apellido, nombres, dpi, fecha_nacimiento, edad, lugar_nacimiento, tipo_sangre, etnia, sexo, nivel_escolar, ocupacion, departamento, municipio, direccion, telefono, email, observacion, hora_ingreso, idioma, alergias)"
                 + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                 
                 PreparedStatement statement;
                 
                 statement = CONEXION.prepareStatement(SQL);
                 statement.setString(1, paciente.getNopaciente());
                 statement.setString(2, paciente.getPrimerapellido());
                 statement.setString(3, paciente.getSegundoapellido());
                 statement.setString(4, paciente.getNombres());
                 statement.setString(5, paciente.getDPI());
                 statement.setDate(6, (java.sql.Date) paciente.fecha());
                 statement.setInt(7, paciente.getEdad());
                 statement.setString(8, paciente.getLugarnacimiento());
                 statement.setString(9, paciente.getTiposangre());
                 statement.setString(10, paciente.getEtnia());
                 statement.setString(11, paciente.getSexo());
                 statement.setString(12, paciente.getNivelescolar());
                 statement.setString(13, paciente.getOcupacion());
                 statement.setString(14, paciente.getDepartamento());
                 statement.setString(15, paciente.getMunicipio());
                 statement.setString(16, paciente.getDireccion());
                 statement.setString(17, paciente.getTelefono());
                 statement.setString(18, paciente.getEmail());
                 statement.setString(19, paciente.getObservacion());
                 statement.setString(20, paciente.getHoraingreso());
                 statement.setString(21, paciente.getIdioma());
                 statement.setString(22, paciente.getAlergias());
                 
                 int filasInsertadas = statement.executeUpdate(); 
                System.out.println("Insertado: " + filasInsertadas);
                
                CONEXION.close();//SIEMPRE SE CIERRA LA CONEXION
                CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
                conexion = null;
                lanzarMensaje("Datos guardados con éxito");
                 
             } catch (SQLException ex) {
             Logger.getLogger(agregarpaciente.class.getName()).log(Level.SEVERE, null, ex);
             lanzarMensaje("Error al grabar datos del paciente: " + ex.getMessage());
             }
              //actualizarTabla();
         }
         paciente pacin = new paciente();
         pacin.setVisible(true);
          this.dispose();
        
    }//GEN-LAST:event_agregarActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
          paciente pacin = new paciente();
         pacin.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
  
    
    private boolean exiteNopaciente(){
        boolean existe = false;
        for(pacientes dato : listapacientes){
            if(dato.getNopaciente().equalsIgnoreCase(nopaciente.getText())){
                existe = true;
            }
        }
        return existe;
    }
    private void lanzarMensaje(String pMensaje) {
        JOptionPane.showMessageDialog(null, pMensaje);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarpaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox<String> alergias;
    private javax.swing.JTextField anio;
    private javax.swing.JButton atras;
    private javax.swing.JTextField departamento;
    private javax.swing.JComboBox<String> dia;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dpi;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> etnia;
    private javax.swing.JTextField horaingreso;
    private javax.swing.JComboBox<String> idioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lugarnacimiento;
    private javax.swing.JComboBox<String> mes;
    private javax.swing.JTextField municipio;
    private javax.swing.JComboBox<String> nivelescolar;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField nopaciente;
    private javax.swing.JTextField observacion;
    private javax.swing.JTextField ocupacionpaciente;
    private javax.swing.JTextField primerapellido;
    private javax.swing.JTextField segundoapellido1;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField telefono;
    private javax.swing.JComboBox<String> tiposangre;
    // End of variables declaration//GEN-END:variables
}
