/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectprogra2;

import clases.pacientes;
import clases.pacientes2;
import clases.postgreeconexion;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anaca
 */
public class Buscarpaciente extends javax.swing.JFrame {

    /**
     * Creates new form Buscarpaciente
     */
    
     paciente pacin = new paciente();
      pacientes2 varpacin = new pacientes2();
      
    public Buscarpaciente() throws SQLException{
         
        initComponents();
         mostrardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nivelescolar1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        ocupacion1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        direccion1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lugarnacimiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        alergias1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        sangre1 = new javax.swing.JComboBox<>();
        telefono1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        observacion1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        horaingreso1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nopaciente1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        primerapellido1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        segundoapellido1 = new javax.swing.JTextField();
        eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        nombres1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        etnia1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        idioma1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        sexo1 = new javax.swing.JComboBox<>();
        dpi1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        municipio1 = new javax.swing.JTextField();
        departamento1 = new javax.swing.JTextField();
        anio2 = new javax.swing.JTextField();
        mes2 = new javax.swing.JComboBox<>();
        dia2 = new javax.swing.JComboBox<>();
        edad3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        horaegreso2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(127, 181, 181));

        nivelescolar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "educación preprimaria (párvulos 1, 2 y 3)", "educación primaria", "educación media (ciclo de educación básica y ciclo de educación diversificada)", "educación universitaria" }));

        jLabel15.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel15.setText("Ocupacion Del Afiliado");

        jLabel16.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel16.setText("Departamento residencia");

        jLabel17.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel17.setText("Municipio residencia");

        jLabel18.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel18.setText("Direccion");

        jLabel19.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel19.setText("Telefono");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel8.setText("Lugar de nacimiento");

        lugarnacimiento.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel9.setText("Alergias");

        alergias1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Alergia a alimentos.", "Alergia a fármacos.", "Asma alérgico.", "Dermatitis atópica.", "Poliposis nasal.", "Rinitis alérgica.", "Urticaria crónica." }));

        jLabel10.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel10.setText("Tipo de Sangre");

        sangre1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Tipo A.", "Tipo B.", "Tipo AB.", "Tipo O.", " " }));

        telefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel20.setText("Email");

        jLabel21.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel21.setText("Observacion");

        jLabel22.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel22.setText("Hora de ingreso");

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        modificar.setBackground(new java.awt.Color(127, 181, 181));
        modificar.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        modificar.setText("MODIFICAR");
        modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel1.setText("No. Afiliado");

        jLabel2.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel2.setText("INFORMACION DEL AFILIADO");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        nopaciente1.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel3.setText("Primer Apellido");

        primerapellido1.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel4.setText("Segundo Apellido");

        segundoapellido1.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        eliminar.setBackground(new java.awt.Color(127, 181, 181));
        eliminar.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel5.setText("Nombres");

        nombres1.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel6.setText("DPI");

        jLabel7.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel7.setText("Fecha de nacimiento");

        jLabel11.setText("Grupo Étnico");

        etnia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "garífuna", "xinka", "achií", "akateco", "awakateco", "chalchiteco", "ch'orti'", "chuj ", "itzá", "ixil ", "jacalteco", "kaqchikel ", "k'iche'", "mam", "mopan", "poqomam", "poqomchi'", "q'anjob'al", "q'eqchi ", "sakapulteco", " sipakapense ", "tektiteko", " tz'utujil ", "uspanteko" }));

        jLabel12.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel12.setText("Idioma");

        idioma1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Inglés ", "Mandarín ", "Hindi", "Español ", "Francés ", "Árabe ", "Bengalí", "Ruso " }));

        jLabel13.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel13.setText("Sexo");

        sexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Masculino", "Femenino", " " }));
        sexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexo1ActionPerformed(evt);
            }
        });

        dpi1.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel14.setText("Nivel Escolar");

        atras.setBackground(new java.awt.Color(127, 181, 181));
        atras.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        atras.setText("ATRAS");
        atras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        mes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-MES-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        dia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-DIA-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        edad3.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel23.setText("Edad");

        jLabel24.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jLabel24.setText("Hora de egreso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(300, 300, 300))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombres1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(dia2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(anio2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addComponent(lugarnacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edad3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addComponent(nopaciente1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(segundoapellido1)
                                        .addComponent(primerapellido1)
                                        .addComponent(dpi1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel23))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(alergias1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(sangre1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(etnia1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(idioma1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13)
                            .addComponent(sexo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addComponent(nivelescolar1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15)
                            .addComponent(ocupacion1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(direccion1)
                            .addComponent(jLabel19)
                            .addComponent(telefono1)
                            .addComponent(jLabel20)
                            .addComponent(email1)
                            .addComponent(jLabel21)
                            .addComponent(observacion1)
                            .addComponent(jLabel22)
                            .addComponent(horaingreso1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(municipio1)
                            .addComponent(departamento1)
                            .addComponent(jLabel24)
                            .addComponent(horaegreso2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(atras)
                        .addGap(273, 273, 273)
                        .addComponent(eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modificar)
                        .addGap(39, 39, 39)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(alergias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sangre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(etnia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(idioma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nivelescolar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ocupacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nopaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(primerapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(segundoapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dpi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(dia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(mes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(anio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lugarnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel23)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(edad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(departamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(municipio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(observacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(horaingreso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(horaegreso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminar)
                            .addComponent(modificar)
                            .addComponent(atras))
                        .addGap(68, 68, 68))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void seleccionaralumno(){
            
        }
    
    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        
       String fecha;
        varpacin.setNopaciente1(nopaciente1.getText());
        varpacin.setPrimerapellido1(primerapellido1.getText());
        varpacin.setSegundoapellido1(segundoapellido1.getText());
        varpacin.setNombres1(nombres1.getText());
        varpacin.setDpi1(dpi1.getText());
         varpacin.setFechanacimiento1(anio2.getText() +"-"+ mes2.getSelectedItem().toString() +"-"+ dia2.getSelectedItem().toString());
        fecha = (anio2.getText() +"-"+ mes2.getSelectedItem().toString() +"-"+ dia2.getSelectedItem().toString());
       varpacin.setEdad1(varpacin.calcularEdad(fecha));
        varpacin.setLugarnacimiento1(lugarnacimiento.getText());
        varpacin.setTiposangre1(sangre1.getSelectedItem().toString());
        varpacin.setEtnia1(etnia1.getSelectedItem().toString());
        varpacin.setSexo1(sexo1.getSelectedItem().toString());
        varpacin.setNivelescolar1(nivelescolar1.getSelectedItem().toString());
        varpacin.setOcupacion1(ocupacion1.getText());
        varpacin.setDepartamento1(departamento1.getText());
        varpacin.setMunicipio1(municipio1.getText());
        varpacin.setDireccion1(direccion1.getText());
        varpacin.setTelefono1(telefono1.getText());
        varpacin.setEmail1(email1.getText());
        varpacin.setObservacion1(observacion1.getText());
        varpacin.setHoraingreso1(horaingreso1.getText());
        varpacin.setHoraegreso1(horaegreso2.getText());
        varpacin.setIdioma1(idioma1.getSelectedItem().toString());
        varpacin.setAlergias1(alergias1.getSelectedItem().toString());
            
       
        
        
        actualizar1(varpacin.getNopaciente1(), varpacin.getPrimerapellido1(), varpacin.getSegundoapellido1(), varpacin.getNombres1(), varpacin.getDpi1(),varpacin.getFechanacimiento1(), varpacin.getLugarnacimiento1(), varpacin.getAlergias1(), 
              varpacin.getTiposangre1(), varpacin.getEtnia1(), varpacin.getIdioma1(), varpacin.getSexo1(), varpacin.getNivelescolar1(), varpacin.getOcupacion1(), varpacin.getDepartamento1(), varpacin.getMunicipio1(), varpacin.getDireccion1(), varpacin.getTelefono1(), 
                varpacin.getEmail1(), varpacin.getObservacion1(), varpacin.getHoraingreso1(), varpacin.getHoraegreso1(), varpacin.getEdad1());
    
          paciente pacin = new paciente();
         pacin.setVisible(true);
          this.dispose();
        
    }//GEN-LAST:event_modificarActionPerformed

    private void actualizar1(String nopaciente, String primerapellido, String segundoapellido, String nombres, String dpi ,String fechanacimiento
    , String lugarnacimiento, String alergias, String tiposangre, String etnia, String idioma, String sexo, String nivelescolar, String ocupacion, 
    String departamento, String municipio, String direccion, String telefono, String email, String observacion, String horaingreso, String horaegreso, int edad){
        
        try {
             postgreeconexion conexion = new postgreeconexion();
            Connection CONEXION = conexion.connectarPostgree();
             Statement statement;
            statement = CONEXION.createStatement(); 
           String SQL = "UPDATE public.registro "+
                     "set primer_apellido = '"+primerapellido+"', segundo_apellido = '"+segundoapellido+"', nombres = '"+nombres+"', dpi = '"+dpi+"', fecha_nacimiento = '"+fechanacimiento+"'"+
                     ", lugar_nacimiento = '"+lugarnacimiento+"', tipo_sangre = '"+tiposangre+"', etnia = '"+etnia+"', sexo = '"+sexo+"', nivel_escolar = '"+nivelescolar+"', ocupacion = '"+ocupacion+"', departamento = '"+departamento+"' ,"+
                     " municipio = '"+municipio+"', direccion = '"+direccion+"', telefono = '"+telefono+"', email = '"+email+"', observacion = '"+observacion+"', hora_ingreso = '"+horaingreso+"', idioma = '"+idioma+"', alergias = '"+alergias+"', hora_egreso = '"+horaegreso+"', edad = '"+edad+"' WHERE no_paciente = '"+nopaciente+"'; ";
             statement.executeUpdate(SQL);
             CONEXION.close();//SIEMPRE SE CIERRA LA CONEXION
            CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
            conexion = null;
          JOptionPane.showMessageDialog(null,"el registro se actualizo", "Exito", JOptionPane.INFORMATION_MESSAGE);
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al actualizar"+e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
   private void mostrardatos() throws SQLException{
     
     
        
            nopaciente1.setEditable(false);
            edad3.setEditable(false);
      nopaciente1.setText(varpacin.getNopaciente1());
      primerapellido1.setText(varpacin.getPrimerapellido1());
      segundoapellido1.setText(varpacin.getSegundoapellido1());
      nombres1.setText(varpacin.getNombres1());
      dpi1.setText(varpacin.getDpi1());
      dia2.setSelectedItem(varpacin.getDia1());
      mes2.setSelectedItem(varpacin.getMes1());
      anio2.setText(varpacin.getAnio1());
      edad3.setText(Integer.toString(varpacin.getEdad1()));
      lugarnacimiento.setText(varpacin.getLugarnacimiento1());
      alergias1.setSelectedItem(varpacin.getAlergias1());
      sangre1.setSelectedItem(varpacin.getTiposangre1());
      etnia1.setSelectedItem(varpacin.getEtnia1());
      idioma1.setSelectedItem(varpacin.getIdioma1());
      sexo1.setSelectedItem(varpacin.getSexo1());
      nivelescolar1.setSelectedItem(varpacin.getNivelescolar1());
      ocupacion1.setText(varpacin.getOcupacion1());
      departamento1.setText(varpacin.getDepartamento1());
      municipio1.setText(varpacin.getMunicipio1());
      direccion1.setText(varpacin.getDireccion1());
      telefono1.setText(varpacin.getTelefono1());
      email1.setText(varpacin.getEmail1());
      observacion1.setText(varpacin.getObservacion1());
      horaingreso1.setText(varpacin.getHoraingreso1());
      horaegreso2.setText(varpacin.getHoraegreso1());
      
      
    
      
       
   }
    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        
        varpacin.setNopaciente1(nopaciente1.getText());
        eliminar(varpacin.getNopaciente1());
          paciente pacin = new paciente();
         pacin.setVisible(true);
          this.dispose();
        
    }//GEN-LAST:event_eliminarActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
          paciente pacin = new paciente();
         pacin.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void telefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono1ActionPerformed

    private void sexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexo1ActionPerformed
    
    private void eliminar(String nopaciente ){
        try {
            
             postgreeconexion conexion = new postgreeconexion();
            Connection CONEXION = conexion.connectarPostgree();
             Statement statement;

            statement = CONEXION.createStatement(); 
            
            String SQL = "DELETE FROM public.registro WHERE no_paciente = '"+nopaciente+"'; ";
            statement.executeUpdate(SQL);
            CONEXION.close();//SIEMPRE SE CIERRA LA CONEXION
            CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
            conexion = null;
            JOptionPane.showMessageDialog(null,"el registro eliminado correctamente", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
 
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null,"Error al eliminar el registro"+e, "Error", JOptionPane.ERROR_MESSAGE);

        }
   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscarpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscarpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscarpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscarpaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                try {
                    new Buscarpaciente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Buscarpaciente.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alergias1;
    private javax.swing.JTextField anio2;
    private javax.swing.JButton atras;
    private javax.swing.JTextField departamento1;
    private javax.swing.JComboBox<String> dia2;
    private javax.swing.JTextField direccion1;
    private javax.swing.JTextField dpi1;
    private javax.swing.JTextField edad3;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField email1;
    private javax.swing.JComboBox<String> etnia1;
    private javax.swing.JTextField horaegreso2;
    private javax.swing.JTextField horaingreso1;
    private javax.swing.JComboBox<String> idioma1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField lugarnacimiento;
    private javax.swing.JComboBox<String> mes2;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField municipio1;
    private javax.swing.JComboBox<String> nivelescolar1;
    private javax.swing.JTextField nombres1;
    private javax.swing.JTextField nopaciente1;
    private javax.swing.JTextField observacion1;
    private javax.swing.JTextField ocupacion1;
    private javax.swing.JTextField primerapellido1;
    private javax.swing.JComboBox<String> sangre1;
    private javax.swing.JTextField segundoapellido1;
    private javax.swing.JComboBox<String> sexo1;
    private javax.swing.JTextField telefono1;
    // End of variables declaration//GEN-END:variables

    private void lanzarMensaje(String datos_guardados_con_éxito) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
