/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectprogra2;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.UIManager;


/**
 *
 * @author anaca
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        InitStyles();
        SetDate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menus = new javax.swing.JPanel();
        mensaje2 = new javax.swing.JLabel();
        barra = new javax.swing.JPanel();
        inicio = new javax.swing.JButton();
        paciente = new javax.swing.JButton();
        reporte = new javax.swing.JButton();
        cabeza = new javax.swing.JPanel();
        mensaje1 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        fondo2 = new javax.swing.JPanel();
        bienvenida = new javax.swing.JLabel();
        descrip = new javax.swing.JLabel();
        pregunta = new javax.swing.JLabel();
        puedes = new javax.swing.JLabel();
        verpacientes = new javax.swing.JLabel();
        agregarpaciente = new javax.swing.JLabel();
        modificarpacientes = new javax.swing.JLabel();
        eliminarpacientes = new javax.swing.JLabel();
        buscarpacientes = new javax.swing.JLabel();
        reportepaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(127, 181, 181));

        fondo.setBackground(new java.awt.Color(127, 181, 181));
        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(1168, 640));

        menus.setBackground(new java.awt.Color(127, 181, 181));
        menus.setForeground(new java.awt.Color(51, 51, 255));
        menus.setPreferredSize(new java.awt.Dimension(270, 640));

        mensaje2.setBackground(new java.awt.Color(127, 181, 181));
        mensaje2.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        mensaje2.setText("HOSPITAL DE DIOS");

        barra.setBackground(new java.awt.Color(127, 181, 181));
        barra.setPreferredSize(new java.awt.Dimension(160, 22));

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        inicio.setBackground(new java.awt.Color(127, 181, 181));
        inicio.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setText("INICIO");
        inicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inicio.setIconTextGap(10);
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        paciente.setBackground(new java.awt.Color(127, 181, 181));
        paciente.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        paciente.setForeground(new java.awt.Color(255, 255, 255));
        paciente.setText("PACIENTES");
        paciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        paciente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        paciente.setMaximumSize(new java.awt.Dimension(42, 20));
        paciente.setMinimumSize(new java.awt.Dimension(42, 20));
        paciente.setPreferredSize(new java.awt.Dimension(42, 20));
        paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteActionPerformed(evt);
            }
        });

        reporte.setBackground(new java.awt.Color(127, 181, 181));
        reporte.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        reporte.setForeground(new java.awt.Color(255, 255, 255));
        reporte.setText("REPORTE & HISTORIAL");
        reporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reporte.setMaximumSize(new java.awt.Dimension(42, 20));
        reporte.setMinimumSize(new java.awt.Dimension(42, 20));
        reporte.setPreferredSize(new java.awt.Dimension(42, 20));
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menusLayout = new javax.swing.GroupLayout(menus);
        menus.setLayout(menusLayout);
        menusLayout.setHorizontalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addGroup(menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menusLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menusLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(menusLayout.createSequentialGroup()
                .addComponent(paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menusLayout.setVerticalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(mensaje2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        cabeza.setBackground(new java.awt.Color(127, 181, 181));
        cabeza.setPreferredSize(new java.awt.Dimension(750, 150));

        mensaje1.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        mensaje1.setText("INICIO / AFILIDADOS  / BUSQUEDAS / REPORTES ");

        hora.setBackground(new java.awt.Color(127, 181, 181));
        hora.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        hora.setText("FECHA: {dayname}  {day} de {month} de {year}");

        javax.swing.GroupLayout cabezaLayout = new javax.swing.GroupLayout(cabeza);
        cabeza.setLayout(cabezaLayout);
        cabezaLayout.setHorizontalGroup(
            cabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezaLayout.createSequentialGroup()
                .addGroup(cabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabezaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cabezaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cabezaLayout.setVerticalGroup(
            cabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mensaje1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        mensaje.setFont(new java.awt.Font("NSimSun", 1, 36)); // NOI18N
        mensaje.setText("Bienvenido ");

        fondo2.setBackground(new java.awt.Color(127, 181, 181));

        bienvenida.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        bienvenida.setText("BIenvenido al programa del Hospital de Dios");

        descrip.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        descrip.setText("Este programa esta diseñado por los mejores Ingenieros del mundo, esta diseñado para llevar un orden en el Hospital ");

        pregunta.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        pregunta.setText("¿Que puedes hacer en el programa?");

        puedes.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        puedes.setText("Puedes : ");

        verpacientes.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        verpacientes.setText("- Ver los pacientes que hay registrados en el sistema.");

        agregarpaciente.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        agregarpaciente.setText("- Agregar pacientes nuevos al sistema.");

        modificarpacientes.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        modificarpacientes.setText("- Modificar la informacion del paciente.");

        eliminarpacientes.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        eliminarpacientes.setText("- Eliminar al paciente.");

        buscarpacientes.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        buscarpacientes.setText("-Buscar al paciente.");

        reportepaciente.setFont(new java.awt.Font("NSimSun", 1, 18)); // NOI18N
        reportepaciente.setText("- Ver el reporte y historial del paciente.");

        javax.swing.GroupLayout fondo2Layout = new javax.swing.GroupLayout(fondo2);
        fondo2.setLayout(fondo2Layout);
        fondo2Layout.setHorizontalGroup(
            fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo2Layout.createSequentialGroup()
                .addGroup(fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo2Layout.createSequentialGroup()
                        .addGroup(fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondo2Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(bienvenida))
                            .addGroup(fondo2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pregunta))
                            .addGroup(fondo2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(puedes))
                            .addGroup(fondo2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(verpacientes))
                            .addGroup(fondo2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(eliminarpacientes))
                            .addGroup(fondo2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(buscarpacientes))
                            .addGroup(fondo2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(agregarpaciente))
                            .addGroup(fondo2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(modificarpacientes))
                            .addGroup(fondo2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(reportepaciente)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(descrip)))
                .addContainerGap())
        );
        fondo2Layout.setVerticalGroup(
            fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descrip)
                .addGap(24, 24, 24)
                .addComponent(pregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(puedes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verpacientes)
                .addGap(18, 18, 18)
                .addComponent(agregarpaciente)
                .addGap(21, 21, 21)
                .addComponent(buscarpacientes)
                .addGap(18, 18, 18)
                .addComponent(eliminarpacientes)
                .addGap(18, 18, 18)
                .addComponent(modificarpacientes)
                .addGap(18, 18, 18)
                .addComponent(reportepaciente)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(cabeza, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menus, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cabeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
         Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inicioActionPerformed

    private void pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteActionPerformed
       
        paciente pacien = new paciente();
        pacien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pacienteActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
        // TODO add your handling code here:
        Reporte reporte = new Reporte();
        reporte.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_reporteActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void SetDate(){
        
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        hora.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'De' MMMM 'De' yyyy", spanishLocale)));
        
    }
    private void InitStyles(){
        
        mensaje.putClientProperty( "FlatLaf.style", "font: 200% $light.font" );
        mensaje.setForeground(Color.black);
        mensaje1.putClientProperty( "FlatLaf.style", "font: 15 $light.font" );
        mensaje1.setForeground(Color.black);
        mensaje2.putClientProperty( "FlatLaf.style", "font: 20 $light.font" );
        mensaje2.setForeground(Color.white);
        hora.putClientProperty( "FlatLaf.style", "font: 200% $light.font" );
        hora.setForeground(Color.black);
        bienvenida.putClientProperty( "FlatLaf.style", "font: 200% $light.font" );
        bienvenida.setForeground(Color.black);
        descrip.putClientProperty( "FlatLaf.style", "font: 15 $light.font" );
        descrip.setForeground(Color.black);
        pregunta.putClientProperty( "FlatLaf.style", "font: 200% $light.font" );
        pregunta.setForeground(Color.black);
        puedes.putClientProperty( "FlatLaf.style", "font: 15 $light.font" );
        puedes.setForeground(Color.black);
        verpacientes.putClientProperty( "FlatLaf.style", "font: 15 $light.font" );
        verpacientes.setForeground(Color.black);
        agregarpaciente.putClientProperty( "FlatLaf.style", "font: 15 $light.font" );
        agregarpaciente.setForeground(Color.black);
        buscarpacientes.putClientProperty( "FlatLaf.style", "font: 15 $light.font" );
        buscarpacientes.setForeground(Color.black);
        eliminarpacientes.putClientProperty( "FlatLaf.style", "font: 15 $light.font" );
        eliminarpacientes.setForeground(Color.black);
        modificarpacientes.putClientProperty( "FlatLaf.style", "font: 15 $light.font" );
        modificarpacientes.setForeground(Color.black);
        reportepaciente.putClientProperty( "FlatLaf.style", "font: 15 $light.font" );
        reportepaciente.setForeground(Color.black);
      //  historialpaciente.putClientProperty( "FlatLaf.style", "font: 15 $light.font" );
       // historialpaciente.setForeground(Color.black);
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarpaciente;
    private javax.swing.JPanel barra;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JLabel buscarpacientes;
    private javax.swing.JPanel cabeza;
    private javax.swing.JLabel descrip;
    private javax.swing.JLabel eliminarpacientes;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondo2;
    private javax.swing.JLabel hora;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JPanel menus;
    private javax.swing.JLabel modificarpacientes;
    private javax.swing.JButton paciente;
    private javax.swing.JLabel pregunta;
    private javax.swing.JLabel puedes;
    private javax.swing.JButton reporte;
    private javax.swing.JLabel reportepaciente;
    private javax.swing.JLabel verpacientes;
    // End of variables declaration//GEN-END:variables
}
