/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectprogra2;

import clases.claslogin;
import java.awt.Color;
import clases.postgreeconexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anaca
 */
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    
    List<claslogin> listalogin;
    claslogin login3;
    public registro() {
        initComponents();
        listalogin = new ArrayList<>();
        login3 = new claslogin();
        colors();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscar2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dpi = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ingresepaciente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        registrar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pass2 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        GUARDAR = new javax.swing.JButton();
        ATRAS = new javax.swing.JButton();
        usuario2 = new javax.swing.JTextField();
        password2 = new javax.swing.JPasswordField();

        buscar2.setText("LOGIN");
        buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar2ActionPerformed(evt);
            }
        });

        jButton2.setText("REGISTRARTE");

        jLabel1.setText("PASSWORD");

        dpi.setBackground(new java.awt.Color(0, 0, 0));
        dpi.setText("USERNAME");

        jTextField1.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        ingresepaciente.setBackground(new java.awt.Color(0, 0, 0));
        ingresepaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ingresepaciente.setText("LOGIN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(127, 181, 181));

        jPanel2.setBackground(new java.awt.Color(127, 181, 181));

        registrar.setBackground(new java.awt.Color(0, 0, 0));
        registrar.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        registrar.setText("REGISTAR NUEVO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(registrar)
                .addGap(139, 139, 139))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(registrar))
        );

        jPanel3.setBackground(new java.awt.Color(127, 181, 181));

        pass2.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        pass2.setText("CONTRASEÑA");

        user2.setBackground(new java.awt.Color(0, 0, 0));
        user2.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        user2.setText("USUARIO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(user2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(pass2)
                .addGap(62, 62, 62))
        );

        GUARDAR.setBackground(new java.awt.Color(127, 181, 181));
        GUARDAR.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        GUARDAR.setText("GUARDAR");
        GUARDAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });

        ATRAS.setBackground(new java.awt.Color(127, 181, 181));
        ATRAS.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        ATRAS.setText("ATRAS");
        ATRAS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATRASActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(password2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(ATRAS)
                        .addGap(63, 63, 63)
                        .addComponent(GUARDAR)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(usuario2))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ATRAS)
                    .addComponent(GUARDAR))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void colors(){
        registrar.setForeground(Color.black);
        user2.setForeground(Color.black);
        pass2.setForeground(Color.black); 
        GUARDAR.setForeground(Color.black);
        ATRAS.setForeground(Color.black);
    } 
    
    private void buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar2ActionPerformed
        // TODO add your handling code here:
        Buscarpaciente buscar2;
        try {
            buscar2 = new Buscarpaciente();
            buscar2.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buscar2ActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        // TODO add your handling code here:
        
         login3 = new claslogin();
         
         if(usuario2.getText().equals("")){
            lanzarMensaje("Debe ingresar un nombre");
         } else if(password2.getText().equals("")){
             lanzarMensaje("Debe ingresar una contraseña");
         }else{
             
             login3.setNombre(usuario2.getText());
             login3.setContra(password2.getText());
             
             listalogin.add(login3);
             
             postgreeconexion conexion = new postgreeconexion();
            Connection CONEXION = conexion.connectarPostgree();
           
                 
             try {
                 
                  String SQL = "INSERT INTO public.login"
                 +"(nombre, contraseña)"
                 + "VALUES (?, ?)";
            
                 PreparedStatement statement;
                 statement = CONEXION.prepareStatement(SQL);
                 
                 statement.setString(1, login3.getNombre());
                 statement.setString(2, login3.getContra());
                 
                 int filasInsertadas = statement.executeUpdate(); 
                System.out.println("Insertado: " + filasInsertadas);
                
                CONEXION.close();//SIEMPRE SE CIERRA LA CONEXION
                CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
                conexion = null;
                lanzarMensaje("Datos guardados con éxito");
                
             } catch (SQLException ex) {
                 Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
                 lanzarMensaje("Error al grabar datos del paciente: " + ex.getMessage());
                 
             }
             
         login log = new login();
        log.setVisible(true);
        this.dispose();
         }
         
        
        
    }//GEN-LAST:event_GUARDARActionPerformed

      private void lanzarMensaje(String pMensaje) {
        JOptionPane.showMessageDialog(null, pMensaje);
    }
    
    private void ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATRASActionPerformed
        // TODO add your handling code here:
        login log = new login();
        log.setVisible(true);
                this.dispose();

    }//GEN-LAST:event_ATRASActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATRAS;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JButton buscar2;
    private javax.swing.JLabel dpi;
    private javax.swing.JLabel ingresepaciente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel pass2;
    private javax.swing.JPasswordField password2;
    private javax.swing.JLabel registrar;
    private javax.swing.JLabel user2;
    private javax.swing.JTextField usuario2;
    // End of variables declaration//GEN-END:variables

    
}
